import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'
import Header from "./components/Header/page";
import Footer from "./components/Footer/page";
import { CartProvider } from "./context/CartContext/CartContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ShopKart",
  description: "Generated by Faseela",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
      
      <CartProvider>
      <Header />
      {children}
      </CartProvider>
      <Footer />
   
        </body>
    </html>
  );
}
